In [1]:
import numpy as np

In [135]:
LIM = 2
END = (LIM, LIM)
INF = 10000

In [136]:
def get_neighbors(r, c):
    
    neighbors = [
        (max(r-1, 0), c),
        (r, min(c+1, LIM)),
        (min(r+1, LIM), c),
        (r, max(c-1, 0))
    ]
    
    # remove self
    neighbors = list(filter(lambda x: x != (r, c), neighbors))
    
    # remove duplicates (edge nodes)
    neighbors = list(set(neighbors))

    return neighbors

In [137]:
cmapping = np.array([
    [1, 8, 3],
    [7, 9, 2],
    [3, 5, 5]
])

In [147]:
visited = np.zeros(shape=(DIM, DIM), dtype='uint16')

distmap = np.ones(shape=(DIM, DIM), dtype='uint16')
distmap.fill(INF)

In [148]:
# init start node
distmap[0, 0] = 0

In [149]:
for i in range(100):
    non_visited = np.where(visited == 0)
    r, c = np.where(distmap == min(distmap[non_visited]))  # pick lowest in 'queue'
    r, c = r[0], c[0]  # just pick first if queues with same value
    
    if (r, c) == END:
        print('Done!')
        break
        
    neighbors = get_neighbors(r, c)

    for neighbor in neighbors:
        nr, nc = neighbor

        if distmap[r, c] + cmapping[nr, nc] < distmap[nr, nc]:
            distmap[nr, nc] = distmap[r, c] + cmapping[nr, nc]
    
    # add to visited
    visited[r, c] = 1

Done!


In [150]:
i

8

In [151]:
visited

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 0]], dtype=uint16)

In [152]:
distmap

array([[ 0,  8, 11],
       [ 7, 16, 13],
       [10, 15, 18]], dtype=uint16)

In [153]:
neighbors

[(0, 1), (1, 0), (1, 2), (2, 1)]

In [62]:
nodes = [(1, (0, 0)), (4, (1, 0)), (5, (0, 1))]

In [63]:
queue = []

In [69]:
heapq.heappush(queue, nodes[0])
heapq.heappush(queue, nodes[2])
heapq.heappush(queue, nodes[1])

In [65]:
current = heapq.heappop(queue)

In [66]:
shortest, position = current
shortest, position

(1, (0, 0))

In [ ]:
visited = []

In [ ]:
shortest, position = current

# get neighbor positions
neighbors = get_neighbors(position)

for neighbor in neighbors:
    if neighbor in visited:
        continue

    r, c = neighbor

    if shortest + mapping[r, c] < dist_map[r, c]:
        dist_map[r, c] = shortest + dist
    
    heapq.heappush(queue, (shortest + dist, neighbor))
    
    # TODO already heap?

    # TODO is visited already?

visited.append(position)

In [72]:
queue

[(1, (0, 0)), (1, (0, 0)), (4, (1, 0)), (4, (1, 0)), (5, (0, 1)), (5, (0, 1))]

In [73]:
set(queue)

{(1, (0, 0)), (4, (1, 0)), (5, (0, 1))}

In [ ]:
# for node in enumerate(queue)
# if pos == neighbor
#.   if value

In [ ]:
# update min
if node in queue
if node val is smaller
heapq.heapreplace

In [76]:
?heapq.heappop

Signature: heapq.heappop(heap, /)
Docstring: Pop the smallest item off the heap, maintaining the heap invariant.
Type:      builtin_function_or_method


In [95]:
a = np.array([
    [100, 100, 2],
    [1, 100, 1]
])

In [96]:
np.where(a == np.min(a))

(array([1, 1]), array([0, 2]))

In [90]:
?np.where

Docstring:
where(condition, [x, y], /)

Return elements chosen from `x` or `y` depending on `condition`.

.. note::
    When only `condition` is provided, this function is a shorthand for
    ``np.asarray(condition).nonzero()``. Using `nonzero` directly should be
    preferred, as it behaves correctly for subclasses. The rest of this
    documentation covers only the case where all three arguments are
    provided.

Parameters
----------
condition : array_like, bool
    Where True, yield `x`, otherwise yield `y`.
x, y : array_like
    Values from which to choose. `x`, `y` and `condition` need to be
    broadcastable to some shape.

Returns
-------
out : ndarray
    An array with elements from `x` where `condition` is True, and elements
    from `y` elsewhere.

See Also
--------
choose
nonzero : The function that is called when x and y are omitted

Notes
-----
If all the arrays are 1-D, `where` is equivalent to::

    [xv if c else yv
     for c, xv, yv in zip(condition, x, y)]

Example